# Generated by Django 5.1 on 2024-09-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='order', to='adminpanel.order'),
            preserve_default=False,
        ),
    ]
