# Generated by Django 5.1 on 2024-09-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
